### ISSUE TITLE
Apply code formatting changes to files

### ISSUE THREAD

**Issue by jedie** [akaihola/pytest-darker#6]
I think it's a good idea to apply code formatting changed to the files. So it's easier to commit the needed changed to fix wrong code formatting ;)

**Comment by Mystic-Mirage** [comment]
This is exactly what the [darker](https://github.com/akaihola/darker) does. Use it if you want to auto-format your code. But the current pytest plugin is just for test purposes. And tests should never make any code changes.

**Comment by akaihola** [comment]
I agree with @Mystic-Mirage. Code modifications should be done by running [darker](https://github.com/akaihola/darker) with one of the following methods:
- manually on the command line
- using a shortcut in an IDE
- automatically by the IDE when saving or shortly after changes
- with [pre-commit](https://pre-commit.com/) when doing a Git commit

I can see how it would be convenient to have code formatted when running `pytest` locally, but as it's common to run it on a CI server as well, I don't think we should introduce code changing capabilities here.
